name: My First CI Pipeline

on: [push]

jobs:
  run-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt  # ← теперь установит и flake8

      # 🔹 НОВЫЙ ШАГ: Запуск линтера
      - name: Run flake8 linter
        run: flake8 . --show-source --statistics

      # 🔹 НОВЫЙ ШАГ: Запуск тестов
      - name: Run pytest
        run: pytest tests/ -v

      - name: Run Hello World
        run: python main.py